print("the quick brown fox jumps over the lazy dog")
print("also enjoy the changes cuz there are lots bud")
print("hello from the macbook")
print('250 202 259 173 130')
print("Hello from the linux vm")
